name: Deploy Backend

on:
  push:
    branches:
      - main
    tags:
      - latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[backend]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check disk space before setup
        run: df -h

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check Docker version
        run: docker --version

      - name: Ensure Docker is running
        run: docker info

      - name: Verify Docker permissions
        run: |
          docker run hello-world
          docker run --rm -v /github/home:/github/home alpine ls /github/home

      - name: Install Serverless Framework globally
        run: npm install -g serverless

      - name: Install Serverless Plugins
        run: |
          cd flask_server
          serverless plugin install -n serverless-python-requirements
          serverless plugin install -n serverless-wsgi

      - name: Install dependencies
        run: |
          cd flask_server
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Cache Serverless Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.serverless
          key: ${{ runner.os }}-serverless-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-serverless-

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Check disk space after installing dependencies
        run: df -h

      - name: Deploy with Serverless
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          cd flask_server
          serverless deploy --stage prod --verbose
