name: Deploy Frontend

on:
  push:
    branches:
      - main
    tags:
      - latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[frontend]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd client
          rm -rf node_modules
          yarn cache clean
          yarn 
          yarn install

      - name: Build frontend
        run: |
          cd client
          REDIRECT_URI=$REDIRECT_URI_PROD \
          PREDICTIONS_ENDPOINT=$PREDICTIONS_ENDPOINT_PROD \
          yarn build --verbose

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 sync client/build s3://spotify-mood-generator-playlist --delete
